### ISSUE TITLE
Add vulnerability checking to the build pipeline

### ISSUE THREAD

**Issue by eganjs** [UKHO/spark-ais-to-raster#14]
Currently there are no vulnerability checks within the check phase of the build.

This should be addressed ASAP, the [OWASP Dependency Check](https://www.owasp.org/index.php/OWASP_Dependency_Check) seems appropriate. To summarise, it scans the dependencies for known CVEs.

There would be additional value in creating a scheduled job within CI that runs this check on a regular basis, nightly for example.

**Comment by JoelClemence** [comment]
Completed by: https://github.com/UKHO/spark-ais-to-raster/pull/36
